export const commonExercises = [
    // Peitoral
    "Supino Reto com Barra",
    "Supino Reto com Halteres",
    "Supino Inclinado com Barra",
    "Supino Inclinado com Halteres",
    "Supino Declinado",
    "Crucifixo Reto",
    "Crucifixo Inclinado",
    "Crossover (Polia Alta)",
    "Crossover (Polia Baixa)",
    "Peck Deck (Voador)",
    "Flexão de Braço",
    "Flexão Diamante",
    "Pull over",

    // Costas
    "Puxada Alta (Pegada Aberta)",
    "Puxada Alta (Pegada Fechada/Supinada)",
    "Puxada Triângulo",
    "Remada Curvada com Barra",
    "Remada Unilateral (Serrote)",
    "Remada Baixa (Triângulo)",
    "Remada Cavalo",
    "Levantamento Terra",
    "Barra Fixa",
    "Graviton",
    "Pulldown com Corda",
    "Dorsal na Polia Alta",

    // Ombros
    "Desenvolvimento com Halteres",
    "Desenvolvimento com Barra (Militar)",
    "Desenvolvimento Arnold",
    "Elevação Lateral",
    "Elevação Frontal com Halteres",
    "Elevação Frontal com Barra",
    "Elevação Frontal com Anilha",
    "Crucifixo Inverso (Posterior)",
    "Face Pull",
    "Remada Alta",
    "Encolhimento de Ombros",

    // Pernas (Quadríceps/Posterior/Glúteo)
    "Agachamento Livre",
    "Agachamento Smith",
    "Agachamento Sumô",
    "Agachamento Frontal",
    "Leg Press 45º",
    "Leg Press Horizontal",
    "Cadeira Extensora",
    "Mesa Flexora",
    "Cadeira Flexora",
    "Stiff",
    "Levantamento Terra Romeno",
    "Afundo (Passada)",
    "Búlgaro",
    "Elevação Pélvica",
    "Cadeira Adutora",
    "Cadeira Abdutora",
    "Panturrilha no Leg Press",
    "Panturrilha Sentado (Gêmeos)",
    "Panturrilha em Pé",

    // Bíceps
    "Rosca Direta com Barra",
    "Rosca Direta com Halteres",
    "Rosca Alternada",
    "Rosca Martelo",
    "Rosca Concentrada",
    "Rosca Scott",
    "Rosca 21",
    "Rosca Inversa",

    // Tríceps
    "Tríceps Corda",
    "Tríceps Barra (Polia)",
    "Tríceps Testa",
    "Tríceps Francês",
    "Tríceps Coice",
    "Mergulho no Banco",
    "Paralelas",

    // Abdômen/Core
    "Abdominal Supra",
    "Abdominal Infra",
    "Abdominal Remador",
    "Prancha Isométrica",
    "Prancha Lateral",
    "Russian Twist",
    "Abdominal na Polia",
    "Elevação de Pernas"
];
